arm_solve_action_server:
  ros__parameters:
    group_name: engineer_arm
    goal_position_tolerance: 0.001
    goal_orientation_tolerance: 0.001
    planning_time: 2.0
    num_planning_attempts: 5

    arm_action_name: move_arm
    joint_states_topic: /joint_states_verbose
    joint_cmd_topic: /joint_commands

    max_velocity_scaling: 0.6
    max_acc_scaling: 0.6

    late_init_delay_ms: 10
    plan_min_interval_ms: 0
